seed: 3141
resolution:
  width: 3840
  height: 5120
  ssaa: 2
camera:
  tilt_deg: 30
  fov_deg: 32
rings:
  - radius: 0.32
    width: 0.0055
    color: "#1E90FF"
    core_intensity: 1.3
    glow_radius: 0.018
    dash: [16, 7]
    ticks:
      every_deg: 15
      length: 0.030
      thickness: 0.0012
      color: "#00B5FF"
      intensity: 1.2
    labels:
      - text: "14.22 Mσ"
        sweep_deg: 60
        offset_deg: 35
        side: outer
        font_size: 38
        tracking: -2.0
        color: "#00B5FF"
        intensity: 1.2
  - radius: 0.48
    width: 0.006
    color: "#FF3B2F"
    core_intensity: 1.45
    glow_radius: 0.024
    dash: [20, 12]
    ticks:
      every_deg: 20
      length: 0.038
      thickness: 0.0015
      color: "#FF6A00"
      intensity: 1.1
    labels:
      - text: "CORE FIELD"
        sweep_deg: 70
        offset_deg: 210
        side: inner
        font_size: 36
        tracking: -1.8
        color: "#FF6A00"
        intensity: 1.25
  - radius: 0.66
    width: 0.007
    color: "#00B5FF"
    core_intensity: 1.1
    glow_radius: 0.028
stars:
  core:
    sigma: 0.20
    alpha: 3.1
    count: 16000
  halo:
    count: 6000
    min_r: 0.34
    max_r: 1.05
    min_separation: 0.0035
  brightness_power: 1.85
  size_min: 0.0015
  size_max: 0.0055
  color_cool: "#1E90FF"
  color_warm: "#FF6A00"
text:
  font: "assets/fonts/Orbitron-Regular.ttf"
post:
  bloom:
    threshold: 1.12
    intensity: 0.3
    radii: [2.0, 4.2, 8.0, 16.0]
  chromatic_aberration:
    k: 0.0005
  vignette: 0.12
  grain:
    strength: 0.011
labels:
  - text: "ARC-Δ"
    radius: 0.52
    angle_deg: 140
    font_size: 40
    tracking: -1.5
    color: "#FFC107"
    intensity: 1.2
  - text: "ACCESS VECTOR"
    radius: 0.75
    angle_deg: 320
    font_size: 34
    tracking: -0.5
    color: "#00B5FF"
    intensity: 1.05
