seed: 5197
resolution:
  width: 3200
  height: 4800
  ssaa: 2
camera:
  tilt_deg: 28
  fov_deg: 30
rings:
  - radius: 0.30
    width: 0.005
    color: "#1E90FF"
    core_intensity: 1.2
    glow_radius: 0.016
    dash: [18, 10]
    ticks:
      every_deg: 20
      length: 0.028
      thickness: 0.0011
      color: "#00B5FF"
      intensity: 1.1
  - radius: 0.52
    width: 0.006
    color: "#FF3B2F"
    core_intensity: 1.3
    glow_radius: 0.022
    dash: [26, 14]
  - radius: 0.74
    width: 0.0065
    color: "#00B5FF"
    core_intensity: 1.0
    glow_radius: 0.024
stars:
  core:
    sigma: 0.18
    alpha: 2.8
    count: 11000
  halo:
    count: 4200
    min_r: 0.36
    max_r: 1.08
    min_separation: 0.003
  brightness_power: 1.75
  size_min: 0.0012
  size_max: 0.0048
  color_cool: "#1E90FF"
  color_warm: "#FF6A00"
text:
  font: "assets/fonts/Orbitron-Regular.ttf"
post:
  bloom:
    threshold: 1.1
    intensity: 0.26
    radii: [1.8, 3.6, 7.2, 14.0]
  chromatic_aberration:
    k: 0.00045
  vignette: 0.10
  grain:
    strength: 0.010
labels:
  - text: "VECTOR 09"
    radius: 0.58
    angle_deg: 60
    font_size: 34
    tracking: -1.0
    color: "#FFC107"
    intensity: 1.1
